### ISSUE TITLE
Duplicate timestamp/nonce combination, possible replay attack. Request rejected.

### ISSUE THREAD

**Issue by BradRuderman** [upwork/python-upwork#15]
I just started getting this error. I tried refreshing my token and everything:

```
{u'status': u'error', u'version': u'0.6', u'errors': [{u'reason': u'access_denied', u'message': u'Duplicate timestamp/nonce combination, possible replay attack. Request rejected.'}]}
```

**Comment by mnovozhylov** [comment]
the issue seems to be related to your side - you're sending the same nonce twice or more, check what you changed recently, because we didn't update the library

**Comment by BradRuderman** [comment]
not sure whats going. I am not sending the token anywhere, I am simply using the library:

```
import os,sys,traceback
from pprint import pprint
import certifi
os.environ['HTTPLIB_CA_CERTS_PATH'] = certifi.where()
import upwork
from datetime import datetime, timedelta

PUBLIC_KEY = ""
SECRET_KEY = ""
ACCESS_TOKEN = ""
ACCESS_TOKEN_SECRET =  ""
ACCOUNT_NAME = ""
client = upwork.Client(PUBLIC_KEY, SECRET_KEY,
                          oauth_access_token=ACCESS_TOKEN,
                          oauth_access_token_secret=ACCESS_TOKEN_SECRET)
provider_id = None
for acct in client.hr.get_companies():
  if acct['name'] == ACCOUNT_NAME':
    provider_id = acct['reference']  

report_dt = datetime.now() - timedelta(days=((365 * 3 )+20))

fields = ["reference","date","date_due","assignment__reference","assignment_name","accounting_entity__reference","accounting_entity_name","buyer_company__reference","buyer_company__id","buyer_company_name","buyer_team__reference","buyer_team__id","buyer_team_name","provider_company__reference","provider_company__id","provider_company_name","provider_team__reference","provider_team__id","provider_team_name","provider__reference","provider__id","provider_name","type","subtype","description","memo","notes","amount"]
query = """
  SELECT {0}
  WHERE date >= {1}
""".format(",".join(fields), report_dt.strftime("%Y%m%d"))

result = client.finreport.get_buyer_companies_billings(provider_id, query)
```

**Comment by mnovozhylov** [comment]
you're probably re-using the same client object for a couple requests, i.e. use the same nonce, signature, etc

**Comment by BradRuderman** [comment]
@mnovozhylov  This has never happened before about 1 week ago. Is there a method I should call after I call get the hr.get_companies() to refresh the token before calling the get_buyer_companies_billing?

**Comment by mnovozhylov** [comment]
@BradRuderman , there were no changes in the library recently (as I wrote, neither on server side), unless you changed smth on your end

**Comment by BradRuderman** [comment]
@mnovozhylov I changed nothing on my end. I am trying to troubleshoot the issue from the code. Do you see anything above that would potentially cause this issue? I only make 2 calls one to get the account reference to use for the get_buy_companies_billing method.

**Comment by mnovozhylov** [comment]
I wrote above what can cause an issue, try:
- sending requests separately as a test
- debugging requests you send

the message you get is a common message for OAuth1.0a protocol, your request(s) can't use the same nonce, but they do somehow - the proposed steps above could help determine a root of the issue

**Comment by BradRuderman** [comment]
@mnovozhylov  I am really stuck here. This error is intermittent (though tends to happen a lot on no shell sessions) and I have been unable to determine the cause. The things to remember i am making 2 API calls:

```
client = upwork.Client(PUBLIC_KEY, SECRET_KEY,
                          oauth_access_token=ACCESS_TOKEN,
                          oauth_access_token_secret=ACCESS_TOKEN_SECRET)
provider_id = None
for acct in client.hr.get_companies():
  if acct['name'] == ACCOUNT_NAME:
    provider_id = acct['reference']  

report_dt = datetime.now() - timedelta(days=((365 * 3 )+20))

fields = ["reference","date","date_due","assignment__reference","assignment_name","accounting_entity__reference","accounting_entity_name","buyer_company__reference","buyer_company__id","buyer_company_name","buyer_team__reference","buyer_team__id","buyer_team_name","provider_company__reference","provider_company__id","provider_company_name","provider_team__reference","provider_team__id","provider_team_name","provider__reference","provider__id","provider_name","type","subtype","description","memo","notes","amount"]
query = """
  SELECT {0}
  WHERE date >= {1}
""".format(",".join(fields), report_dt.strftime("%Y%m%d"))

result = client.finreport.get_buyer_companies_billings(provider_id, query)

```

I understand this is a common oauth issue though I don't really do anything oauth related. I tried redoing the auth dance to get new tokens/secrets but the ids don't change even after I revoke the access and re-auth.

Any guidance on specific debugging I can do that might help would be very helpful. Thanks!

**Comment by mnovozhylov** [comment]
@BradRuderman I don't see any "common oauth issue" - please, post in this tracker only information related to the library directly, and not to your own code.

**Comment by vlzinch** [comment]
Hi, i also get same error, have tried this on few pc, same issue. 
As i see in module connection.py , after timeout, it tries make request with exact same parameters without creation new timestamp/nonce.

Regards,
Vlad

**Comment by BradRuderman** [comment]
@vlzinch  Yes confirmed I am getting this intermittently every day and have been unable to troubleshoot exact cause. I have tried emailing UpWork but they just keep reiterating its my code.

**Comment by govindad** [comment]
thanks @vlzinch you are right this is indeed an issue with python-upwork

**Comment by mnovozhylov** [comment]
@vlzinch / @govindad , please, don't confuse other users with non-proofed information!
`connection.py` is not a part of python-upwork library, it's a part of urllib3. Moreover, python-upwork provides a possibility to setup a timeout parameter when you create an instance. Try to increase your timeouts, might timeout happens because of internet lags between your server and Upwork's servers.

**Comment by govindad** [comment]
@mnovozhylov you are suggesting that "upwork.exceptions.HTTP403ForbiddenError: HTTP Error 403: Code 403: Duplicate timestamp/nonce combination, possible replay attack. Request rejected." is caused by a timeout error?

**Comment by vlzinch** [comment]
@mnovozhylov, to be clear - your SDK doesn't work, and you don't want to understand why, looks like you just took money from Upwork and now dont' want spent your time to fix it. 
SDK doesn't work, and thats all, no matter where error exact, it if crash on three rows of code, so its quality quite poor.
@govindad, @BradRuderman  suggest use just http request, now this api.

**Comment by mnovozhylov** [comment]
@vlzinch , thank you for your feedback!

I believe as a developer/engineer you understand that a tool may depend on many libraries and it means that some of them could be maintained by 3d parties. I pointed out you that `urllib3` library is not owned by Upwork and can't be changed, but it provides a flexible way to specify a timeout for a connection. `python-upwork` provide an option to use that functionality by end consumers.

We definitely pay attention on this problem in future versions to make the library more independent. Right now the best way would be to fix your software using valid timeouts.

**Comment by ppolewicz** [comment]
This started happening again this morning to me. The client code has not been touched for at least two weeks, it is executed twice per hour from crontab for about 3 months. Finally my tool found a profile which could not have been downloaded in 5s ( !? ) and then the error in this thread started to show.

@mnovozhylov the problem is that request retry logic is left to urllib3 (https://github.com/upwork/python-upwork/blob/4aa78cbfaffd97e7bee82c6fcbb334e181a39fc7/upwork/client.py#L121), while for oauth-signed requests it should call `get_oauth_params()` between retries. This IS a bug in python-upwork, which is expected to not cause oauth authentication failure during retries it supports. To fix it, python-upwork should implement the retry logic on its own, re-signing the request between retries, instead of relying on simple urllib3 retries which are not suitable for oauth signed requests.

**Comment by mnovozhylov** [comment]
@ppolewicz , thank you for your feedback. `python-upwork` library doesn't contain any retry logic intentionally. If urllib3 logic doesn't suit your needs, you can always handle an error on your side (on client's side) and implement retry logic according to the needs of your application, because different consumers may require different needs, and it doesn't make overload the library with additional logic and tons of configuration parameters.

**Comment by ppolewicz** [comment]
@mnovozhylov could you please explain what does this line do:
https://github.com/upwork/python-upwork/blob/4aa78cbfaffd97e7bee82c6fcbb334e181a39fc7/upwork/client.py#L121 ?

**Comment by mnovozhylov** [comment]
@ppolewicz , please, follow the `urllib3` documentation in case you need details what that option does.

**Comment by vlzinch** [comment]
@mnovozhylov hope you work only on this project, and we wount need to work with any other your script   :)
@ppolewicz easier create normal request workaround than use this 'library', if you want - message me, i can share simply examples.

**Comment by mnovozhylov** [comment]
@ppolewicz , eventually, I wasn't clear enough. Let me repeat - {{python-upwork}} doesn't contain any own retry logic by design. `urllib3` does contain and the line you referred really specifies two retries to handle only possible network issues.
As you mentioned above, it started happening recently. Maybe, you have a network lags that force the urllib3 library resending the request. Please, try to check in that direction.

@vlzinch , appreciate your feedback. The idea of this library is providing a simple basic(!) and flexible(!) way to access Upwork API. Said "flexible", I mean that extending error handling and adding any additional functionality is up to the end consumer according to his needs.

**Comment by JonnyOThan** [comment]
For anyone coming across this issue, I was banging my head against it for a few hours until I finally used Fiddler to look at the requests and responses.

The server was responding with a 302 redirect, and my http library was helpfully following the redirect and sending the same headers - which of course included the duplicate nonce and timestamp.

**Comment by mnovozhylov** [comment]
@JonnyOThan , thank you for shared this information with the community!
If possible, please, contact our Support Team at (http://support.upwork.com/) and share the details (the full request with the parameters and headers, as well as, the full response with body and headers will be required) about the request which was redirected. We will investigate it accordingly and check what we could refine on our end in this regard.

**Comment by morgansamson** [comment]
@JonnyOThan - Can you please share more details on how you resolved this error? For example, how did you get your http library to update the nonce and timestamp values upon redirect?

I've run into this same error with the Java-Upwork library. I've encountered it occasionally even just using the example code provided with the library while importing it into a Scala project. I'm using the scalaj.http library. While the implementation and http libraries might be different, I'm really curious about your approach to see if I can adapt it on my end.

**Comment by ppolewicz** [comment]
you need to disable the retry mechanism built into your http backend, generate a new oauth token and issue a new request by yourself

**Comment by morgansamson** [comment]
Thanks @ppolewicz - I'll look into replicating a similar approach with the http library I'm using!
